src/objects/Contacts__c.object
<CustomObject>
    <label>Contacts</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Contacts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contacts__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receipt_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Receipt date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Store__c.object
<CustomObject>
    <fields>
        <fullName>End_Period__c</fullName>
        <label>End Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Period__c</fullName>
        <label>Start Period</label>
        <type>Date</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Number_of_days__c</fullName>
        <label>Number of days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Accounting period</label>
</CustomObject>

src/classes/CongratulationsTest.cls
@isTest
private class CongratulationsTest {
    @isTest
    static void TestEmail() {
        Store__c st =  new Store__c(Name = 'Store', Start_Period__c = System.today(), End_Period__c = System.today() + 30);
        insert st;
        Test__c t = new Test__c(Number_of_days__c = 15);
        insert t;
        Contacts__c cnt = new Contacts__c(Name = 'Test');
        Product__c pr = new Product__c(Name='Test',  Receipt_date__c=System.today(), Store__c = st.Id, Contacts__c= cnt.Id);
        Test.startTest();
        Database.SaveResult result = Database.insert(pr);
        //insert pr;
        Test.stopTest();
        List<FeedItem> feedItems = [SELECT Id FROM FeedItem WHERE CreatedById = :UserInfo.getUserId() ORDER BY CreatedDate DESC];
        System.assertEquals( 0, feedItems.size());
    }

}