src/objects/Contacts__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Contacts</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Contacts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contacts__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost_with_discount__c</fullName>
        <label>Cost with discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Link_to_Image__c</fullName>
        <label>Link to Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OkController.cls
public class OkController {
    public string BuyID {get; set;}
    public List<Product__c> Records {get; set;}
    public OkController() {
        BuyID = ApexPages.currentPage().getParameters().get('id');
        Records =
            [select Name, Title__c, Cost_with_discount__c, Price__c, Link_to_Image__c, Contacts__c from Product__c where Id = :BuyID];
        /*for(Product__c pr : Records) {
Contacts__c c = [Select Email__c From Contacts__c Where Id = :pr.Contacts__c];
EmailManager.sendMail(c.Email__c, 'Congratulations on your purchase', 
'Your ship name is ' + pr.Name + ' and it is price is ' +  pr.Price__c);
}*/
        Send();
    }
    
    public PageReference Home() {
        for(Product__c pr : Records) {
            Contacts__c c = [Select Email__c From Contacts__c Where Id = :pr.Contacts__c];
            EmailManager.sendMail(c.Email__c, 'Congratulations with your purchase', 
                                  'Your ship name is ' + pr.Name + ' and it is price is ' +  pr.Price__c);
        }
        PageReference pg = new PageReference('/apex/TestTable');
        return pg;
    }
    public void Send() {
        for(Product__c pr : Records) {
            Contacts__c c = [Select Email__c From Contacts__c Where Id = :pr.Contacts__c];
            EmailManager.sendMail(c.Email__c, 'Congratulations with your purchase', 
                                  'Your ship name is ' + pr.Name + ' and it is price is ' +  pr.Price__c);
        }
    }
}