src/objects/Contacts__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Contacts</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Contacts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contacts__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receipt_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Receipt date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Store__c.object
<CustomObject>
    <fields>
        <fullName>End_Period__c</fullName>
        <label>End Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Period__c</fullName>
        <label>Start Period</label>
        <type>Date</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestOkController.cls
@isTest
private class TestOkController {
    @isTest static void Test() {
        Store__c st = new Store__c(Name = 'Store', Start_Period__c = System.today(), End_Period__c = System.today() + 30);
        insert st;
        Contacts__c cn = new Contacts__c(Name = 'Test', Email__c = 'test@mail.ru');
        insert cn;
        Product__c pr = new Product__c(Name='Test', Receipt_date__c=System.today(), Store__c = st.Id, Contacts__c = cn.Id);
        OkController ok = new OkController();
            System.assert(ok.Records != null);
        ok.Records.add(pr);
        PageReference pref = ok.Home();
    }
}