src/objects/Contacts__c.object
<CustomObject>
    <label>Contacts</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contacts__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost_with_discount__c</fullName>
        <label>Cost with discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <recordTypes>
        <fullName>Sold</fullName>
        <active>true</active>
        <label>Sold</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Store__c.object
<CustomObject>
    <fields>
        <fullName>End_Period__c</fullName>
        <label>End Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Period__c</fullName>
        <label>Start Period</label>
        <type>Date</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Number_of_days__c</fullName>
        <label>Number of days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Accounting period</label>
</CustomObject>

src/classes/TestBuyController.cls
@isTest(SeeAllData=true)
private class TestBuyController {
    @isTest static void TestController() {
        BuyController bc = new BuyController();
        RecordType[] rt1 = [SELECT Id, Name from RecordType where name = 'Sold' AND SObjectType = 'Product__c'];
        Store__c st = new Store__c(Name = 'Store', Start_Period__c = System.today(), End_Period__c = System.today() + 30);
        Contacts__c cn = new Contacts__c(Name = 'Test');
        insert cn;
        insert st;
        if(rt1.size() > 0){
            Product__c Pr = new Product__c(Name='Test', Store__c = st.Id, Amount__c = 15, RecordTypeId = rt1[0].Id, Contacts__c = cn.Id,
                                          Price__c = 100, Cost_with_discount__c = 0);
            insert Pr;
            Test__c t = new Test__c(Number_of_days__c = 15);
            bc.BuyId = Pr.Id;
        }
        PageReference prTest = bc.buy();
        System.assert(bc.dd != null);
        System.assert(bc.Records != null);
    }
    
}