src/objects/Discount__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestscheduledDiscount.cls
@isTest
private class TestscheduledDiscount {
    static testmethod void TestDiscountChange() {
        Discount__c dt = new Discount__c(Name = 'Test',
                                         Start_Date__c = System.now(),
                                         End_Date__c = System.now()+1);
        insert dt;
        
        Test.startTest();
        System.schedule('ScheduleApexTest', '0 0 0 11 10 ? 2019', new scheduledDiscount());
        Test.stopTest();
        
        List<Task> tsk = [SELECT Id FROM Task WHERE WhatId = :dt.Id];
        System.assertNotEquals(1, tsk.size());
    }
}