src/objects/Discount__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchDiscountTest.cls
@isTest private class BatchDiscountTest {
   @testSetup
    static void setup() {
        Discount__c dt = new Discount__c(Name = 'Test',
                                        Start_Date__c = System.now(),
                                        End_Date__c = System.now()+1);
        insert dt;
    }
    static testmethod void test() {
        Test.startTest();
        BatchDiscount bd = new BatchDiscount();
        Id batchId = Database.executeBatch(bd);
        Test.stopTest();
        Discount__c actual = [select Status__c from Discount__c where Name = 'Test' limit 1];
        System.assertEquals('Not Started', actual.Status__c);
    }
}