src/objects/Discount__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchDiscount.cls
global class BatchDiscount implements 
    Database.Batchable<sObject>, Database.Stateful {
        
        global final String STATUS_1 = 'Not Started';
        global final String STATUS_2 = 'Ended';
        global final String STATUS_3 = 'Active';
        
        global Database.QueryLocator start(Database.BatchableContext bc) {
            return Database.getQueryLocator('Select Start_Date__c, End_Date__c, Status__c ' +
                                           'From Discount__c');}
        global void execute(Database.BatchableContext bc, List<Discount__c> scope){
            List<Discount__c> disc = new List<Discount__c>();
            for(Discount__c d : scope) {
                if (d.Start_Date__c > system.today()) {
                    d.Status__c = STATUS_1;
                } else if(d.End_Date__c < system.today()) {
                    d.Status__c = STATUS_2;
                } else {
                    d.Status__c = STATUS_3;
                }
                disc.add(d);
            }
            update disc;
        }
        global void finish(Database.BatchableContext bc){
             System.debug('Batch complete!');
        }
}