src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receipt_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Receipt date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/raw_material__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receipt_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Receipt date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>raw material</relationshipLabel>
        <relationshipName>raw_material</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>raw material</label>
    <nameField>
        <label>raw Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>raw material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StoreAttachTest.cls
@isTest
private class StoreAttachTest {
    @isTest static void TestR1() {
        raw_material__c raw = new raw_material__c(Name='Test', Name__c='Test', Title__c='Main', Receipt_date__c=System.today(), Store__c = 'a026F00001NPqVTQA1');
        Test.startTest();
        insert raw;
        Test.stopTest();
        System.assertNotEquals('a026F00001NPqVTQA1', raw.Store__c);
    }
        @isTest static void TestR2() {
        raw_material__c raw = new raw_material__c(Name='Test', Name__c='Test', Title__c='Main', Receipt_date__c=date.parse('12/27/2020'), Store__c = 'a026F00001NPqVTQA1');
        Test.startTest();
        insert raw;
        Test.stopTest();
        System.assertNotEquals('a026F00001NPqVTQA1', raw.Store__c);
    }
        @isTest static void TestP1() {
        Product__c pr = new Product__c(Name='Test', Receipt_date__c=System.today(), Store__c = 'a026F00001NPqVTQA1');
        Test.startTest();
        insert pr;
        Test.stopTest();
        System.assertNotEquals('a026F00001NPqVTQA1', pr.Store__c);
    }
        @isTest static void TestP2() {
        Product__c pr = new Product__c(Name='Test', Receipt_date__c=date.parse('12/27/2020'), Store__c = 'a026F00001NPqVTQA1');
        Test.startTest();
        insert pr;
        Test.stopTest();
        System.assertNotEquals('a026F00001NPqVTQA1', pr.Store__c);
    }
}