src/objects/raw_material__c.object
<CustomObject>
    <fields>
        <fullName>Receipt_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Receipt date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>raw material</relationshipLabel>
        <relationshipName>raw_material</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>raw material</label>
    <nameField>
        <label>raw Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>raw material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Store__c.object
<CustomObject>
    <fields>
        <fullName>End_Period__c</fullName>
        <label>End Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Period__c</fullName>
        <label>Start Period</label>
        <type>Date</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Number_of_days__c</fullName>
        <label>Number of days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Accounting period</label>
</CustomObject>

src/classes/Store_update_raw.cls
public class Store_update_raw {
        public static string add(raw_material__c Obj) {
        List<Store__c> st = [SELECT ID FROM Store__c WHERE Start_Period__c <= :Obj.Receipt_date__c AND End_Period__c >= :Obj.Receipt_date__c];
        if(st.size() == 0) { 
            Test__c mc = Test__c.getOrgDefaults();
            Store__c store = new Store__c(Name = 'New Store',
                                          Start_Period__c = system.today(),
                                          End_Period__c = system.today() + mc.Number_of_days__c.intValue());
            insert store;
            return store.Id;
        }
        else {
            return st.get(0).Id;
        }
    }
}